#!/bin/sh
echo
echo
echo
echo
echo
echo
echo
echo
echo "This macro gives an overview of the results generated by the"
echo "macro runFast.noList.sh."
echo
echo "The t-test is used to compare the results of each simulation"
echo "to results from a baseline simulation bin-by-bin.  In general"
echo "the maximum absolute value of the t-tests should be between"
echo "2 and 5.  The random nature of the data may lead to a higher"
echo "value on occasion, but the higher value should disappear if"
echo "the simulation and analysis are rerun."
echo
echo
echo

echo "Press return to continue."
read DUMMY
echo
echo
echo
echo
echo
echo
echo

cd PET3d
./analyzePET3d.noList.sh
cd ..

echo "Press return to continue."
read DUMMY
echo
echo
echo
echo
echo

cd PET2d
./analyzePET2d.sh
cd ..

echo "Press return to continue."
read DUMMY
echo
echo
echo
echo
echo

cd PETblock
./analyzePETblock.sh
cd ..

echo "Press return to continue."
read DUMMY
echo
echo
echo
echo
echo

cd TOFPET
./analyzeTOFPET.sh
cd ..

echo "Press return to continue."
read DUMMY
echo
echo
echo
echo
echo

cd DHCI
./analyzeDHCI.noList.sh
cd ..

echo "Press return to continue."
read DUMMY
echo
echo
echo
echo
echo

cd SPECT
./analyzeSPECT.noList.sh
cd ..

echo "Press return to continue."
read DUMMY
echo
echo
echo
echo
echo

cd SPECTcone
./analyzeSPECTcone.sh
cd ..

echo "Press return to continue."
read DUMMY
echo
echo
echo
echo
echo

cd SPECTfan
./analyzeSPECTfan.sh
cd ..

echo
echo
echo "resultsFast.noList complete."
echo
